"""empty message

Revision ID: 195ead875d75
Revises: 00d8f13d815f
Create Date: 2018-08-01 16:33:43.863070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195ead875d75'
down_revision = '00d8f13d815f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haiku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('haiku', sa.String(length=500), nullable=True),
    sa.Column('sold_to_payment_request', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_haiku_sold_to_payment_request'), 'haiku', ['sold_to_payment_request'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_haiku_sold_to_payment_request'), table_name='haiku')
    op.drop_table('haiku')
    # ### end Alembic commands ###
